spring:
  cloud:
    nacos:
      discovery:
        server-addr: 1.94.249.22:8848 #nacos地址
        namespace: ai-dream
        group: DEFAULT_GROUP
        enabled: true
        username: ps
        password: star
      config:
        server-addr: 1.94.249.22:8848 #nacos配置中心地址
        namespace: ai-dream
        group: DEFAULT_GROUP # 默认组名，可以根据需要更改
        file-extension: yaml # 文件扩展名，默认为properties
    openfeign:
      httpclient:
        connection-timeout: 20000
  config:
    import: nacos:/ai-dream.yaml?refreshEnabled=true
logging:
  level:
    org.springframework.security: DEBUG
    RocketmqClient: ERROR
    io:
      netty: ERROR
server:
  tomcat:
    threads:
      max: 200




